try{
/*
 * Do not edit this file by hand
 */ 
var Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart_module = angular.module('Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart', ['adf.provider','builder','builder.components','validator.rules'])
  .config(function(dashboardProvider){
    dashboardProvider
      .widget('Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart', {
        title: 'Task003Start',
        editTitle :'Task003Start Settings',
        description: 'Task003Start Description',
        templateUrl: '/<<CONTEXT_ROOT>>/Task003Start/views/view.xhtml',
        controller: 'Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart_Controller',
        controllerAs: 'Task003Start',
        frameless : 'false',
        previewImage: '/<<CONTEXT_ROOT>>/images/Task003Start/default.png',
        edit: {
          templateUrl: '/<<CONTEXT_ROOT>>/Task003Start/views/settings.xhtml'
        },
        application : "TaskDevelopmentProject0002A",
        gadgetGroup: "TaskDevelopmentProject0002A",
        id: "Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart",
        widgetName : "Task003Start",
        defaults:{ "title": "Task003Start",
  	      "structure": "6-6",
  	      "rows": [{
  	        "columns": [{
  	          "styleClass": "col-md-12",
  	          "widgets": [ {
  	              "type": "Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart",
  	              "title": "",
  	              "config": {
  	            	  "params":{
  	            	         
                                },
  	            	  "title":""
  	              	}
  	            }]
  	        }]
  	      }]
  	  }
              });
  });
   if(angular.module('Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart')){
    	wmBCGadgets.requires.push('Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart');
    	
    	Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart_module.run(function(){
    		try{
	    		var dep=['builder','builder.components','validator.rules'];//define list of dependencies
	        	for(var module in dep){
	        		if(dep.hasOwnProperty(module)){
	        			angular.module(dep[module]);
	        			Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart_module.requires.push(dep[module]);
	        		}
	        	}
    		}catch(exception){
    			console.error("Gadget Exception: "+exception);
    		}
    	});
    	 
    }

}
catch(exception){
	angular.module('wmBCGadgets').run(function(dashboard){
		dashboard.widgets["Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart"]= Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart_module;
	})
	Task003Start_a60ea484_fcbc_4e27_b3d2_852831c7328fStart_module["error"]=exception;
	throw new GadgetException(exception);
}